# Generated by Django 4.1.6 on 2023-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=250)),
                ("lastname", models.CharField(max_length=250)),
                ("age", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=50)),
                ("password", models.CharField(max_length=250)),
                ("mobile", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
