# Generated by Django 4.1.6 on 2023-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_register_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")], max_length=10
            ),
        ),
    ]
